In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df=sns.load_dataset("titanic")

In [16]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [8]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [14]:
df.drop(['class', 'who',  'deck', 'embark_town','adult_male',
       'alive'],axis=1,inplace=True)

In [20]:
df['age'].fillna(df["age"].mean(),inplace=True)

C:\Users\youra\AppData\Local\Temp\ipykernel_9872\2077405870.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df["age"].mean(),inplace=True)

In [24]:
df.dropna(subset=["embarked"],inplace=True)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [34]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [44]:
df=df.astype(int)

In [38]:
df["sex"]=le.fit_transform(df["sex"])

In [40]:
df["embarked"]=le.fit_transform(df["embarked"])

In [46]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

In [48]:
x_data=df.drop("survived",axis=1)

In [50]:
y_data=df["survived"]

In [52]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=42)

In [56]:
from sklearn.linear_model import LogisticRegression

In [58]:
model=LogisticRegression()

In [60]:
model.fit(x_train,y_train)

C:\Users\youra\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [62]:
y_pred=model.predict(x_test)

In [66]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [72]:
accuracy_score(y_test,y_pred)*100

80.33707865168539

In [74]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [76]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.85      0.83      0.84       109\n           1       0.74      0.77      0.75        69\n\n    accuracy                           0.80       178\n   macro avg       0.79      0.80      0.79       178\nweighted avg       0.81      0.80      0.80       178\n'

In [80]:
 df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0           0       3    1   22      1      0     7         2      0
1           1       1    0   38      1      0    71         0      0
2           1       3    0   26      0      0     7         2      1
3           1       1    0   35      1      0    53         2      0
4           0       3    1   35      0      0     8         2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...
886         0       2    1   27      0      0    13         2      1
887         1       1    0   19      0      0    30         2      1
888         0       3    0   29      1      2    23         2      0
889         1       1    1   26      0      0    30         0      1
890         0       3    1   32      0      0     7         1      1

[889 rows x 9 columns]

In [88]:
from sklearn.preprocessing import StandardScaler

In [92]:
scaler=StandardScaler()

In [96]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.fit_transform(x_test)

In [98]:
from sklearn.neighbors import KNeighborsClassifier

In [102]:
knn_model=KNeighborsClassifier(n_neighbors=5)

In [106]:
knn_model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [110]:
y_pred_knn= knn_model.predict(x_test_scaled)

In [114]:
accuracy_score(y_test,y_pred_knn)

0.7808988764044944

In [118]:
from sklearn.tree import DecisionTreeClassifier

In [120]:
model_dt=DecisionTreeClassifier(random_state=42)

In [122]:
model_dt.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [126]:
y_pred_dt=model_dt.predict(x_test_scaled)

In [128]:
accuracy_score(y_test,y_pred_dt)

0.7696629213483146

In [130]:
from sklearn.svm import SVC

In [134]:
model_svm=SVC(kernel='rbf')

In [138]:
model_svm.fit(x_train_scaled,y_train)

SVC()

In [142]:
y_pred_svc=model_svm.predict(x_test_scaled)

In [144]:
accuracy_score(y_test,y_pred_svc)

0.8258426966292135

In [146]:
import os
print(os.getcwd())

C:\Users\youra\OneDrive\Desktop\git work\polynomial_regression_model